%GenerateDailyBloombergInternationalFraSwapData1
clear all %#ok<CLSCR>
close all
drawnow


currencyStr = 'GBP';
%currencyStr = 'USD';
%currencyStr = 'ZAR';
%currencyStr = 'EUR';


tickerNameVec = BloombergFraSwapTickersForBlock( currencyStr  );

securityStrCell = {tickerNameVec.ticker};
%fieldStrCell = {'BID'};

fieldStrCell = {'px_last'};


%startDateVal = fix( now-22 );
%endDateVal = fix( now-11 );

startDateVal = datenum('1-jan-2014');
endDateVal = datenum('15-jan-2014');

%hashStr = MyDataHash( {securityStrCell , fieldStrCell, startDateVal, endDateVal} )
%
% if now < datenum('736819')...
%  %03-May-2017 14:45:07 && strcmp( getenv('computername'), 'KEITH-FORBES-LP' ) %InteractivePanther
% %DEBUGGING OR TEST CODE GOES HERE
% %Autogenerated by C:\Dropbox (Fairtree Newlands)\SharedRmbamHf\Matlab\IfNow.m
% %tempsave, stop
% end

dateVector = startDateVal:endDateVal;

for dateLoop = length(dateVector):-1:1
    
    
    dateVal = dateVector(dateLoop);
    
    if IsBusinessDay( dateVal, currencyStr )
        
        
        disp(  qdatestr(dateVal) )
        verbosityLevel = 0;
        [bloomHistVec, responseHistStr] = ProfessorKettledrumRequest( securityStrCell , fieldStrCell, dateVal, dateVal, verbosityLevel );
        
        outCell = {bloomHistVec.security};
        
        [missingCell, indVec] = setdiff( securityStrCell, outCell );
        
        disp(  missingCell  )
        for jj = 1:length(indVec)
            ind = indVec(jj);
           fprintf('missing %s (%s)\n', tickerNameVec(ind).ticker, tickerNameVec(ind).name  );
        end

        
        dirname = [DropboxFairtreeNewlandsDir(), '\SharedRmbamHf\Data\Bloomberg\FraSwap\', currencyStr];
        filename = FormFilename('%s/FraSwap%s%s.mat',dirname, currencyStr, datestr(dateVal, 29)  );
        disp(  filename )
        
        %stop
    end
    
    
end




